/*******************************************************************************
Projet  :  Automatiser les rapports de ventes avec SQL
   Chinook Database - Version 1.4.5
   Script: Chinook_MySql.sql
   Description: Creates and populates the Chinook database.
   DB Server: MySql
   Author: Japhet Allah-N'diguim
   License: https://github.com/lerocha/chinook-database/blob/master/LICENSE.md
********************************************************************************/

/*******************************************************************************
  WARNING: This file was generated by a tool and changes to this file
           will be lost when this file is regenerated.
********************************************************************************/

/*******************************************************************************
   Drop database if it exists
********************************************************************************/
DROP DATABASE IF EXISTS `Rapport_De_Vents`;


/*******************************************************************************
   Create database
********************************************************************************/
CREATE DATABASE `Rapport_De_Vents`;


USE `Rapport_De_Vents`;

/*******************************************************************************
   Create Tables
********************************************************************************/
CREATE TABLE `Album`
(
    `AlbumId` INT NOT NULL,
    `Title` NVARCHAR(160) NOT NULL,
    `ArtistId` INT NOT NULL,
    CONSTRAINT `PK_Album` PRIMARY KEY  (`AlbumId`)
);
